//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCAMS.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCAMS_UserSettingsCasino
    {
        public long Id { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<bool> IsAllowToPay { get; set; }
    }
}
