//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCAMS.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCAMS_User
    {
        public long Id { get; set; }
        public string AspNetUserId { get; set; }
        public long PersonId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public long UserTypeId { get; set; }
        public Nullable<bool> IsOTPEnable { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
