//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCAMS.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCAMS_Account
    {
        public long Id { get; set; }
        public Nullable<long> PersonId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> AccountLevelId { get; set; }
        public Nullable<long> AccountTypeId { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<decimal> CasinoBalance { get; set; }
        public Nullable<decimal> TotalCasinoBalance { get; set; }
        public Nullable<int> Commission { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Withdrawal { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
